name: Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치 push 시 배포

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/node_backend:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/node_backend:latest

    - name: SSH to EC2 and Restart Containers
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /opt/app
          sudo docker compose pull
          sudo docker compose down
          sudo docker compose up -d